openapi: 3.0.0
info:
  title: Ame Pro ERP Integration
  description: This API describes the endpoints published by Ame Pro ERP that receives
    calls from Horus Ame Pro reverse proxy
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/vyniciuspontes/ame-pro-erp-integration/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Reverse Proxy
  description: External resources sent from Horus to Ame Pro ERP
paths:
  /api/integration/b2sky/order:
    post:
      tags:
      - Reverse Proxy
      summary: Order submissions sent to Ame Pro ERP
      operationId: createOrders
      requestBody:
        $ref: '#/components/requestBodies/Orders'
      responses:
        200:
          description: Successfully created order
components:
  schemas:
    OrderCollection:
      type: object
      properties:
        platform:
          type: string
          description: Integration platform name
        sellerName:
          type: string
          description: Seller name
        order_package:
          type: array
          items:
            $ref: '#/components/schemas/OrderPackage'
    OrderPackage:
      type: object
      properties:
        external_id:
          type: string
          description: Order external Id
        order:
          $ref: '#/components/schemas/Order'
    Order:
      type: object
      properties:
        operator:
          type: string
          description: PDV order operator
        session_id:
          type: string
          description: Operator session id
        store_id:
          type: string
          description: PDV Store id
        pos_id:
          type: string
          description: PDV id
        code:
          type: string
          description: Order identification code
        channel:
          type: string
          description: Sale channel where the order has been placed
        placed_at:
          type: string
          description: Date and time when the order has been placed
          format: date-time
        updated_at:
          type: string
          description: Date and time when the order has been updated
          format: date-time
        shipping_carrier:
          type: string
          description: Order shipping carrier
        shipping_method:
          type: string
          description: Order shipping method
        shipping_cost:
          type: number
          description: Total order shipping cost
        calculation_type:
          type: string
          description: Freight estimation method on order purchase
        estimated_delivery:
          type: string
          description: Order estimated delivery
          format: date-time
        estimated_delivery_shift:
          type: string
          description: Day shift for scheduled delivery (eg. null for non scheduled
            orders)
          enum:
          - MORNING
          - AFTERNOON
          - NIGHT
        items:
          type: array
          description: Ordered items
          items:
            $ref: '#/components/schemas/Item'
        customer:
          $ref: '#/components/schemas/Customer'
        shipping_address:
          $ref: '#/components/schemas/Address'
        billing_address:
          $ref: '#/components/schemas/Address'
        status:
          $ref: '#/components/schemas/Status'
        sync_status:
          type: string
          description: Order synchronization status (eg. relates to seller platform
            integration status)
          enum:
          - SYNCED
          - NOT_SYNCED
          - ERROR
        total_ordered:
          type: number
          description: Total ordered value
        interest:
          type: number
          description: Order interest value
        payment:
          type: array
          items:
            $ref: '#/components/schemas/Payment'
        refund:
          $ref: '#/components/schemas/Refund'
        invoices:
          type: array
          description: Order invoice list
          items:
            $ref: '#/components/schemas/Invoice'
        shipments:
          type: array
          items:
            $ref: '#/components/schemas/Shipment'
    Refund:
      type: object
      properties:
        cancelation_reason:
          type: string
          description: Cancelation Reason
          default: "1"
        sefaz_protocol_number:
          type: string
          description: Nfce cancelation protocol number
        sefaz_authorization_date:
          type: string
          description: Nfce cancelation authorization date
        contingency:
          type: boolean
          description: Indicates if Nfce was canceled in contingency
      description: Refund details when PDV sends CANCELED status
    Address:
      type: object
      properties:
        full_name:
          type: string
          description: Address full name
        street:
          type: string
          description: Address street name
        number:
          type: string
          description: Address number
        detail:
          type: string
          description: Address details
          deprecated: true
        complement:
          type: string
          description: Address complement (additional info)
        reference:
          type: string
          description: Address reference
        neighborhood:
          type: string
          description: Address neighborhood
        city:
          type: string
          description: Address city
        region:
          type: string
          description: Address region
        country:
          type: string
          description: Address country (ISO 3166 code)
        postcode:
          type: string
          description: Address post code
        phone:
          type: string
          description: Address main phone number
        secondary_phone:
          type: string
          description: Address secondary phone number
    Customer:
      type: object
      properties:
        name:
          type: string
          description: Customer name
        email:
          type: string
          description: Customer email address
        date_of_birth:
          type: string
          description: Customer date of birth
        gender:
          type: string
          description: Customer gender
        vat_number:
          type: string
          description: Customer VAT identification number
        phones:
          type: array
          description: Customer phone list
          items:
            type: string
        state_registration:
          type: string
          description: Customer state registration (in case of a company customer)
    Item:
      type: object
      properties:
        id:
          type: string
          description: Item identification code (eg. product or product variation
            SKU code)
        product_id:
          type: string
          description: Item product identification code (eg. product SKU code)
        name:
          type: string
          description: Item name
        qty:
          type: integer
          description: Item purchased quantity
        original_price:
          type: number
          description: Item original price
        special_price:
          type: number
          description: Item purchased price
        shipping_cost:
          type: number
          description: Item shipping cost
        commercial_unit:
          type: string
          enum:
            - PC
            - KG
            - UNID
            - M
    Invoice:
      type: object
      properties:
        key:
          pattern: ^\d{44}$
          type: string
          description: Brazilian electronic invoice key (NFe key)
        number:
          pattern: ^\d{9}$
          type: string
          description: Invoice number
        line:
          pattern: ^\d{3}$
          type: string
          description: Invoice line (serie number)
        issue_date:
          type: string
          description: Invoice issue date
          format: date-time
        contingency:
          type: boolean
          description: Indicates if Nfce was emitted in contingency (ONLY PDV)
    Shipment:
      type: object
      properties:
        code:
          type: string
          description: Shipment identification code
        items:
          type: array
          items:
            $ref: '#/components/schemas/ShipmentItem'
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/ShipmentTrack'
    ShipmentItem:
      required:
      - qty
      - sku
      type: object
      properties:
        sku:
          type: string
          description: Shipment item SKU code
        qty:
          type: integer
          description: Shipment item quantity
    ShipmentTrack:
      required:
      - carrier
      - code
      - method
      type: object
      properties:
        code:
          type: string
          description: Shipment track code
        carrier:
          type: string
          description: Shipping carrier
        method:
          type: string
          description: Shipping method
        url:
          type: string
          description: Tracking URL
    Payment:
      type: object
      properties:
        method:
          type: string
          description: Payment method
        description:
          type: string
          description: Payment description
        value:
          type: number
          description: Payment value
        parcels:
          type: integer
          description: Number of installments
        cashback_amount_value:
          type: string
          description: Cashback Value (Only AME_DIGITAL method)
        ame_operation_id:
          type: string
          description: Cashback Value (Only AME_DIGITAL method)
        nsu:
          type: string
          description: Transaction nsu
        transaction_id:
          type: string
          description: Id da transação
        change:
          type: string
          description: change if payment is in cash (Only MONEY method)
        transaction_date:
          type: string
          description: Payment transaction date
          format: date-time
        status:
          type: string
          description: Payment status
        card_issuer:
          type: string
          description: Card issuer
        autorization_id:
          type: string
          description: Authorization ID
        sefaz:
          $ref: '#/components/schemas/Sefaz'
    Sefaz:
      type: object
      properties:
        id_payment:
          type: string
        name_payment:
          type: string
        id_card_issuer:
          type: string
        name_card_issuer:
          type: string
        type_integration:
          type: string
        payment_indicator:
          type: string
    Status:
      required:
      - code
      - label
      - type
      type: object
      properties:
        code:
          type: string
          description: Order status code
        label:
          type: string
          description: Order status label
        type:
          type: string
          description: Order status type (see StatusType)
  requestBodies:
    Orders:
      description: Order Package Collection
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderCollection'
          examples:
            New Order From PDV:
              value:
                platform: B2SKY
                order_package:
                - external_id: "001101201906031355002"
                  order:
                    operator: "000036001357"
                    session_id: "1558539023088"
                    store_id: "001"
                    pos_id: "101"
                    code: "001101201906031355001"
                    channel: POS
                    placed_at: 2019-05-22T15:30:23.088Z
                    updated_at: 2019-05-22T15:30:23.088Z
                    items:
                    - id: "7896341101987"
                      product_id: "7896341101987"
                      name: Bacon
                      qty: 1
                      original_price: 1.99
                      special_price: 0.99
                    customer:
                      vat_number: "12345678909"
                      phones: []
                    status:
                      code: Cancelled
                      label: Cancelado (SkyHub)
                      type: CANCELED
                    total_ordered: 1.99
                    discount: 0
                    payments:
                    - method: MONEY
                      value: 0.99
                      change: 0
                      transaction_date: 2019-05-22T15:25:23.088Z
                    - method: AME_DIGITAL
                      value: 0.5
                      parcels: 1
                      ame_operation_id: "654321"
                      nsu: "123456"
                      transaction_id: "123456789"
                      transaction_date: 2019-05-22T15:26:23.088Z
                    - method: DEBIT_ACCOUNT
                      value: 0.25
                      parcels: 1
                      transaction_date: 2019-05-22T15:27:23.088Z
                    - method: CREDIT_CARD
                      value: 0.25
                      parcels: 1
                      transaction_date: 2019-05-22T15:28:23.088Z
                    refund:
                      cancelation_reason: "1"
                      sefaz_protocol_number: "333190000484874"
                      sefaz_authorization_date: 2019-05-23T18:36:18-03:00
                      contingency: false
                    invoices:
                    - key: NFe33181233014556020200654000000000271995355507
                      number: "19454"
                      line: "1"
                      issue_date: 2019-05-22T15:30:23.087Z
                      contingency: false
            Refund Order From PDV:
              value:
                platform: B2SKY
                order_package:
                  - external_id: 001101201906031355002
                    order:
                      operator: '000036001357'
                      session_id: '1558539023088'
                      store_id: '001'
                      pos_id: '101'
                      code: 001101201906031355001
                      channel: POS
                      placed_at: '2019-05-22T15:30:23.088Z'
                      updated_at: '2019-05-22T15:30:23.088Z'
                      items:
                        - id: '7896341101987'
                          product_id: '7896341101987'
                          name: Bacon
                          qty: 1
                          original_price: 1.99
                          special_price: 0.99
                      customer:
                        vat_number: '12345678909'
                        phones: []
                      status:
                        code: Cancelled
                        label: Cancelado (SkyHub)
                        type: CANCELED
                      total_ordered: 1.99
                      discount: 0
                      payments:
                        - method: MONEY
                          value: 0.99
                          change: 0
                          transaction_date: '2019-05-22T15:25:23.088Z'
                        - method: AME_DIGITAL
                          value: 0.5
                          parcels: 1
                          ame_operation_id: '654321'
                          nsu: '123456'
                          transaction_id: '123456789'
                          transaction_date: '2019-05-22T15:26:23.088Z'
                        - method: DEBIT_ACCOUNT
                          value: 0.25
                          parcels: 1
                          transaction_date: '2019-05-22T15:27:23.088Z'
                        - method: CREDIT_CARD
                          value: 0.25
                          parcels: 1
                          transaction_date: '2019-05-22T15:28:23.088Z'
                      refund:
                        cancelation_reason: '1'
                        sefaz_protocol_number: '333190000484874'
                        sefaz_authorization_date: '2019-05-23T18:36:18-03:00'
                        contingency: false
                      invoices:
                        - key: NFe33181233014556020200654000000000271995355507
                          number: '19454'
                          line: '1'
                          issue_date: '2019-05-22T15:30:23.087Z'
                          contingency: false

      required: true
