openapi: 3.0.0
# Added by API Auto Mocking Plugin
info:
  description: This API describes the endpoints published by Horus Ame Pro PDV
  version: "1.0.0"
  title: Horus Ame Pro PDV

servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: http://homolog-b2w.horus-ame-pro-pdv.atlas.b2w


tags:
  - name: Orders

paths:

  orders:
    post:
      security:
        - basicAuth: []
      summary: Send order to ERP
      operationId: orderPackagePDV
      tags: [Orders]
      requestBody:
        $ref: '#/components/requestBodies/Order'


      responses:
        200:
          description: Successfully sent order to ERP
          headers:
            Chain-Id:
              schema:
                type: string
              example: '5cf57a39e8288600070ef0b6-16-51-MONDAY-3-2019'

        400:
          description: Format error on some property of the body
          headers:
            Chain-Id:
              schema:
                type: string
              example: '5cf57a39e8288600070ef0b6-16-51-MONDAY-3-2019'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidBodyError'

        504:
          description: The server did not receive a timely response from the ERP server
          headers:
            Chain-Id:
              schema:
                type: string
              example: '5cf57a39e8288600070ef0b6-16-51-MONDAY-3-2019'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatwayTimeoutError'

components:

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:

    InvalidBodyError:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        path:
          type: string
          example: /orders
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: Field 'sale.saleItem.products[].discounts[].value' has an invalid format

    GatwayTimeoutError:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        path:
          type: string
          example: /orders
        status:
          type: integer
          example: 504
        error:
          type: string
          example: Gatway Timeout
        message:
          type: string
          example: The server was acting as a gateway or proxy and did not receive a timely response from the upstream server

    Order:
      type: object
      properties:
        _id:
          type: string
        couponNumber:
          type: string
        storeId:
          type: string
        posId:
          type: string
        companyId:
          type: string
        accountingDay:
          type: string
          format: date
        endDate:
          type: string
        operator:
          type: string
        refund:
          type: object
          properties:
            cancelReason:
              type: string
            contingency:
              type: boolean
            originalSaleId:
              type: string
            originalCouponNumber:
              type: string
            sefazAuthorizationDate:
              type: string
              format: date-time
            sefazProtocolNumber:
              type: string
        sale:
          type: object
          properties:
            saleItem:
              type: object
              properties:
                customer:
                  type: object
                  properties:
                    documentType:
                      type: string
                    document:
                      type: string
                invoice:
                  type: object
                  properties:
                    createDate:
                      type: string
                    number:
                      type: integer
                      format: int32
                    serie:
                      type: integer
                      format: int32
                    contingency:
                      type: boolean
                    sefazAuthorization:
                      type: object
                      properties:
                        accessKey:
                          type: string
                        authorizationDate:
                          type: string
                          format: date-time
                        protocolNumber:
                          type: string
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      cartRegisterDate:
                        type: string
                      commercialUnit:
                        type: string
                      departmentCode:
                        type: string
                      description:
                        type: string
                      discounts:
                        type: array
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                            value:
                              type: string
                            discountType:
                              type: string
                      ean:
                        type: string
                      externalCode:
                        type: string
                      imeis:
                        type: array
                        items:
                          type: string
                      priceType:
                        type: string
                      ncm:
                        type: string
                      cfop:
                        type: string
                      taxInfo:
                        type: object
                        properties:
                          approximateTotalValue:
                            type: string
                          icms:
                            type: object
                            properties:
                              aliquot:
                                type: string
                              productOriginCode:
                                type: string
                              modalityBaseCalculation:
                                type: string
                              simplesNacionalSituation:
                                type: string
                          ipi:
                            type: object
                            properties:
                              taxSituation:
                                type: string
                              baseCalculationValue:
                                type: string
                              aliquot:
                                type: string
                              value:
                                type: string
                              unitValue:
                                type: string
                          pis:
                            type: object
                            properties:
                              aliquotSt:
                                type: string
                              baseCalculationValue:
                                type: string
                              baseCalculationValueSt:
                                type: string
                              taxSituation:
                                type: string
                              aliquot:
                                type: string
                              aliquotReais:
                                type: string
                              aliquotReaisSt:
                                type: string
                              value:
                                type: string
                              valueSt:
                                type: string
                          cofins:
                            type: object
                            properties:
                              aliquotSt:
                                type: string
                              baseCalculationValue:
                                type: string
                              baseCalculationValueSt:
                                type: string
                              taxSituation:
                                type: string
                              aliquot:
                                type: string
                              aliquotReais:
                                type: string
                              aliquotReaisSt:
                                type: string
                              value:
                                type: string
                              valueSt:
                                type: string
                      quantity:
                        type: integer
                        format: int32
                      sequenceCouponNumber:
                        type: integer
                        format: int32
                      totalDiscountValue:
                        type: string
                      totalProductValue:
                        type: string
                      unitValue:
                        type: string
                payments:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: string
                      change:
                        type: number
                      date:
                        type: string
                saleItemTotal:
                  type: object
                  properties:
                    quantity:
                      type: integer
                      format: int32
                    totalDiscountValue:
                      type: string
                    totalSale:
                      type: string
                    totalValue:
                      type: string
        sessionId:
          type: string
        startDate:
          type: string
        zoneId:
          type: string

  requestBodies:
    Order:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
          examples:
            New Order:
              value:
                _id: b8317770-6373-4569-bfd4-bf11102442b7
                couponNumber: 001101201906031355001
                storeId: '001'
                posId: '101'
                companyId: AME
                accountingDay: '2019-05-22'
                endDate: '2019-05-22T15:30:23.088Z'
                operator: '000036001357'
                sale:
                  saleItem:
                    customer:
                      documentType: CPF
                      document: '12345678909'
                    invoice:
                      createDate: '2019-05-22T15:30:23.087Z'
                      number: 19454
                      serie: 1
                      contingency: false
                      sefazAuthorization:
                        accessKey: NFe33181233014556020200654000000000271995355507
                        authorizationDate: '2018-08-24T16:16:38-03:00'
                        protocolNumber: '333160000150516'
                    products:
                    - cartRegisterDate: '2019-05-22T15:30:23.088Z'
                      comercialUnit: '1'
                      departmentCode: ''
                      description: Bacon
                      discounts:
                      - code: PERCENTAGE_DISCOUNT
                        value: '1.99'
                        discountType: PERCENTAGE_DISCOUNT
                      ean: '7896341101987'
                      externalCode: '7896341101987'
                      imeis: []
                      priceType: NORMAL
                      ncm: '49019900'
                      cfop: '5102'
                      taxInfo:
                        approximateTotalValue: '2.42'
                        icms:
                          aliquot: '0'
                          productOriginCode: '0'
                          modalityBaseCalculation: '3'
                          simplesNacionalSituation: '300'
                        ipi:
                          taxSituation: '99'
                          baseCalculationValue: '10'
                          aliquot: '0'
                          value: '0'
                          unitValue: '0'
                        pis:
                          aliquotSt: '0'
                          baseCalculationValue: '10'
                          baseCalculationValueSt: '0'
                          taxSituation: '99'
                          aliquot: '0'
                          aliquotReais: '0'
                          aliquotReaisSt: '0'
                          value: '0'
                          valueSt: '0'
                        cofins:
                          aliquotSt: '0'
                          baseCalculationValue: '10'
                          baseCalculationValueSt: '0'
                          taxSituation: '99'
                          aliquot: '0'
                          aliquotReais: '0'
                          aliquotReaisSt: '0'
                          value: '0'
                          valueSt: '0'
                      quantity: 1
                      sequenceCouponNumber: 0
                      totalDiscountValue: '0.00'
                      totalProductValue: '1.99'
                      unitValue: '1.99'
                    payments:
                    - type: MONEY
                      value: '0.99'
                      change: '0'
                      date: '2019-05-22T15:25:23.088Z'
                    - type: AME_DIGITAL
                      value: '0.50'
                      ameOperationId: '654321'
                      cashbackAmountValue: '0.05'
                      installments: 1
                      nsu: '123456'
                      transactionId: '123456789'
                      date: '2019-05-22T15:26:23.088Z'
                    - type: DEBIT
                      value: '0.25'
                      installments: 1
                      date: '2019-05-22T15:27:23.088Z'
                    - type: CREDIT
                      value: '0.25'
                      installments: 1
                      date: '2019-05-22T15:28:23.088Z'
                    saleItemTotal:
                      quantity: 1
                      totalDiscountValue: '0.00'
                      totalSale: '1.99'
                      totalValue: '1.99'
                sessionId: '1558539023088'
                startDate: '2019-05-22T15:30:23.088Z'
                zoneId: America/Fortaleza
            Refund Order:
              value:
                _id: b8317770-6373-4569-bfd4-bf11102442b8
                couponNumber: 001101201906031355002
                storeId: '001'
                posId: '101'
                companyId: AME
                accountingDay: '2019-05-22'
                endDate: '2019-05-22T15:30:23.088Z'
                operator: '000036001357'
                refund:
                  cancelReason: '1'
                  contingency: false
                  originalSaleId: b8317770-6373-4569-bfd4-bf11102442b7
                  originalCouponNumber: 001101201906031355001
                  sefazAuthorizationDate: '2019-05-23T18:36:18-03:00'
                  sefazProtocolNumber: '333190000484874'
                sale:
                  saleItem:
                    customer:
                      documentType: CPF
                      document: '12345678909'
                    invoice:
                      createDate: '2019-05-22T15:30:23.087Z'
                      number: 19454
                      serie: 1
                      contingency: false
                      sefazAuthorization:
                        accessKey: NFe33181233014556020200654000000000271995355507
                        authorizationDate: '2018-08-24T16:16:38-03:00'
                        protocolNumber: '333160000150516'
                    products:
                    - cartRegisterDate: '2019-05-22T15:30:23.088Z'
                      commercialUnit: '1'
                      departmentCode: ''
                      description: Bacon
                      discounts:
                      - code: PERCENTAGE_DISCOUNT
                        value: '1.99'
                        discountType: PERCENTAGE_DISCOUNT
                      ean: '7896341101987'
                      externalCode: '7896341101987'
                      imeis: []
                      priceType: NORMAL
                      ncm: '49019900'
                      cfop: '5102'
                      taxInfo:
                        approximateTotalValue: '2.42'
                        icms:
                          aliquot: '0'
                          productOriginCode: '0'
                          modalityBaseCalculation: '3'
                          simplesNacionalSituation: '300'
                        ipi:
                          taxSituation: '99'
                          baseCalculationValue: '10'
                          aliquot: '0'
                          value: '0'
                          unitValue: '0'
                        pis:
                          aliquotSt: '0'
                          baseCalculationValue: '10'
                          baseCalculationValueSt: '0'
                          taxSituation: '99'
                          aliquot: '0'
                          aliquotReais: '0'
                          aliquotReaisSt: '0'
                          value: '0'
                          valueSt: '0'
                        cofins:
                          aliquotSt: '0'
                          baseCalculationValue: '10'
                          baseCalculationValueSt: '0'
                          taxSituation: '99'
                          aliquot: '0'
                          aliquotReais: '0'
                          aliquotReaisSt: '0'
                          value: '0'
                          valueSt: '0'
                      quantity: 1
                      sequenceCouponNumber: 0
                      totalDiscountValue: '0.00'
                      totalProductValue: '1.99'
                      unitValue: '1.99'
                    payments:
                    - type: MONEY
                      value: '0.99'
                      change: '0'
                      date: '2019-05-22T15:25:23.088Z'
                    - type: AME_DIGITAL
                      value: '0.50'
                      ameOperationId: '654321'
                      cashbackAmountValue: '0.05'
                      installments: 1
                      nsu: '123456'
                      transactionId: '123456789'
                      date: '2019-05-22T15:26:23.088Z'
                    - type: DEBIT
                      value: '0.25'
                      installments: 1
                      date: '2019-05-22T15:27:23.088Z'
                    - type: CREDIT
                      value: '0.25'
                      installments: 1
                      date: '2019-05-22T15:28:23.088Z'
                    saleItemTotal:
                      quantity: 1
                      totalDiscountValue: '0.00'
                      totalSale: '1.99'
                      totalValue: '1.99'
                sessionId: '1558539023088'
                startDate: '2019-05-22T15:30:23.088Z'
                zoneId: America/Fortaleza


      description: Order Package Collection
      required: true
